CREATE TYPE "AssetPlatformUsage" AS ENUM ('CUSTOMER_ASSIGNABLE', 'RUN_BASE_ONLY', 'HIDDEN');

ALTER TABLE "Asset"
ADD COLUMN "platformUsage" "AssetPlatformUsage" NOT NULL DEFAULT 'CUSTOMER_ASSIGNABLE';
