ALTER TABLE "BarSale"
ADD COLUMN "totalBaseRevenueCents" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "autoDiscountCents" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "manualDiscountCents" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "manualDiscountReason" VARCHAR(200);

ALTER TABLE "BarSaleItem"
ADD COLUMN "baseUnitPriceCents" INTEGER,
ADD COLUMN "baseRevenueCents" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "autoDiscountCents" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "manualDiscountCents" INTEGER NOT NULL DEFAULT 0;
